"use strict";

const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const checkOnly = process.argv.includes("--check");

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
}

function stableJson(value) {
  return JSON.stringify(value, null, 2);
}

const prompts = readJson("data/prompts.json");
const examples = readJson("data/examples.json");

const output = [
  "/* Generated by tools/build-data-js.js. Do not edit by hand. */",
  `"use strict";`,
  `window.NIRAY_PROMPTS = ${stableJson(prompts)};`,
  `window.NIRAY_EXAMPLES = ${stableJson(examples)};`,
  ""
].join("\n");

const outputPath = path.join(root, "assets", "js", "data.js");
fs.mkdirSync(path.dirname(outputPath), { recursive: true });

if (checkOnly) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  if (current !== output) {
    console.error("assets/js/data.js is out of date. Run npm run build:data.");
    process.exit(1);
  }
  console.log("assets/js/data.js is up to date.");
} else {
  fs.writeFileSync(outputPath, output, "utf8");
  console.log("Generated assets/js/data.js");
}

